#!/bin/bash

BACKUP_FILE="$HOME/Documents/workspace-utils/db_downloads/rsds-test-db-b1065"
DB_NAME=rsds_web_development
USERNAME=dipenchauhan
PORT=32768

TENANT_DOMAIN="app.localhost"
SCRUB_MODE="local"

# -----------------------------------------
# DON'T CHANGE ANYTHING BELOW THIS LINE
# -----------------------------------------

# Set the Rails environment variable
export RAILS_ENV=development
export SKIP_TEST_DATABASE=true

# Function to check the exit status and exit if any command fails
check_status() {
    if [ $? -ne 0 ]; then
        echo -e "\033[1;31mError occurred in the previous step. Exiting script.\033[0m"
        exit 1
    fi
}

# Function to print messages in yellow
print_yellow() {
    echo -e "\033[1;33m$1\033[0m"
}

# Check if the file exists
if [ -e "$BACKUP_FILE" ]; then
    print_yellow "File exists: $BACKUP_FILE"
else
    print_yellow "File does not exist: $BACKUP_FILE"
    exit 1  # Exit with an error code
fi

clear
print_yellow "Running script to load local db from a backup..."

print_yellow "Loading db in localhost environment from full backup ($BACKUP_FILE)..."

# Drop the database
print_yellow "Dropping db..."
DISABLE_DATABASE_ENVIRONMENT_CHECK=1 rake db:drop
check_status

# Re-create the database
print_yellow "Re-creating db..."
rake db:create
check_status

# Create heroku_ext schema
print_yellow "Creating heroku_ext schema..."
psql --host=localhost --port=$PORT --username=$USERNAME --dbname=$DB_NAME -c "CREATE SCHEMA heroku_ext;"
check_status

# Restore the database
print_yellow "Restoring db..."
pg_restore --if-exists --verbose --clean --no-acl --no-owner --host=localhost --port=$PORT --username=$USERNAME --dbname=$DB_NAME $BACKUP_FILE
check_status

# Run migrations
print_yellow "Running migrations..."
rails db:migrate
check_status

# Scrub the data
print_yellow "Scrubbing data..."
rake database:update_db_after_restore[$TENANT_DOMAIN,$SCRUB_MODE]
check_status

# Uncomment the next line if needed
# rails api_rsds:add_integration_client

print_yellow "Database load script completed successfully."
